### ISSUE TITLE
Add option for indicator icon to change colour when tracking time

### ISSUE THREAD

**Issue by ePaulo** [projecthamster/hamster#227]
Please add option to have task indicator icon change colour depending on whether time tracking is on or off.  Thank you for creating such a useful program; I use it in conjunction with Get Things GNOME for my contract work.

**Comment by nchachereau** [comment]
Hi there,
what version of Hamster are you using, and what indicator? If you don't know the answers to those questions: what distribution are you using, and what desktop environment (Gnome, Unity, etc)?

**Comment by ePaulo** [comment]
The information you requested is:
   hamster-indicator 0.1+037dd2e-0ubuntu2
   hamster-applet 2.91.3+git20120514.b9fec3e1-1ubuntu1
   desktop environment is Unity
   OS is ubuntu 14.04

Right now, the indicator is a *blue* clock(?) icon on black background.  
It would be useful if the colour changed from a static 'blue' to 
something different, like a static 'green' version of the clock icon, or 
an animated blue 'running clock' icon, or green arrow over the static 
blue clock... something to visually indicate when time is being tracked.

Thank you for looking into this request :-)

**Comment by nchachereau** [comment]
Okay. With the version you are using, you can activate a "glow" for what you want to do. See the end of [this article](http://www.webupd8.org/2011/07/install-hamster-indicator-time-tracking.html):

```gconftool-2 --set "/apps/hamster-indicator/icon_glow" --type bool "true"```

Hamster is currently ongoing major changes, and the new indicator also will also have the option you request (with an actual window to enable and disable the option, instead of keeping it hidden).

Cheers!
