### ISSUE TITLE
The package is of bad quality

### ISSUE THREAD

**Issue by orschiro** [projecthamster/hamster#256]
Dear all, 

Thank you very much for your work on hamster!

I wanted to install the latest version 2.0-rc1-2 on Ubuntu 15.04. 

However, the software center warns me with the following message: 

![image](https://cloud.githubusercontent.com/assets/170947/10109792/7fd1cc14-63c9-11e5-8980-3049098a0c3b.png)

Is it safe to continue?

Thankfully,

Robert

**Comment by toupeira** [comment]
Well as I mention on the release page this is just an experimental package for convenience purposes, it doesn't follow the Debian packaging policy at all and that's why you get this warning.

You can also build a package yourself by cloning the repository and running `sudo checkinstall ./waf install`.

**Comment by toupeira** [comment]
Oh and proper packaging is a work in progress, see #252.

**Comment by orschiro** [comment]
@toupeira 

Thanks for the reference! I will follow the issue. Maybe I can help at some point. 

Warmly,

Robert
