### ISSUE TITLE
Track time more precisely, allow showing minutes instead of hours

### ISSUE THREAD

**Issue by tstriker** [projecthamster/hamster#26]
original: https://bugzilla.gnome.org/show_bug.cgi?id=675833

**Comment by jollyrogue** [comment]
Two decimal points makes more sense then just one decimal point. 15min and 45min are two of the four major time checkpoints, and they aren't accurately displayed in the overview since it rounds to one decimal point.

Configurable decimal places would be nice, but just switching to two decimal places would be great.

**Comment by ederag** [comment]
Minutes are now displayed. This is a [v2.1.1](https://github.com/projecthamster/hamster/releases/tag/v2.1.1) screenshot:
![image](https://user-images.githubusercontent.com/10962809/50036092-55c09900-0006-11e9-85aa-eb379e5139c2.png)
