### ISSUE TITLE
Overview window opens in the background

### ISSUE THREAD

**Issue by fturco** [projecthamster/hamster#283]
Steps to reproduce:
1. Open an Iceweasel/Firefox window and maximize it
2. Click on Show Overview in Hamster GNOME Shell extension

Result: A notification appears saying: Time Tracker, January 11-17 2016 is ready; Hamster Overview window stays in the background.

Expected result: Hamster Overview window appears in the foreground.

I'm using the following versions:
- GNOME 3.18.2
- hamster-time-tracker 1.04-2
- hamster-shell-extension-git 20151020.g030fb5a-1

**Comment by SlowMo24** [comment]
I would like to confirm and add, that this is also the case for adding earlier tasks and adding new tasks.

**Comment by ederag** [comment]
Seems to be fixed (tested with 2.1.1). Please ask here otherwise.

**Comment by GeraldJansen** [comment]
I have the same issue of the overview window not rising to the foreground even with current master. If there is an open overview window but it is partially or fully hidden behind another window, there is a notification that "hamster-windows-service is ready" the first time hamster is restarted either from the command line, a menu launcher or from hamster-shell-extension "Show Overview", and the current window does not rise to the foreground. Subsequent launches of hamster are silent and the open window remains hidden.

**Comment by ederag** [comment]
Overview opens correctly in the foreground, from the command line (I do not use the extension).

Actually, the issue can be reproduced from the command-line:
`hamster toggle` does nothing.

This command calls
https://github.com/projecthamster/hamster/blob/b200d1007e43495fb6c466bca6c6dd478ae49bd7/src/hamster-cli#L184-L185
which goes to
https://github.com/projecthamster/hamster/blob/b200d1007e43495fb6c466bca6c6dd478ae49bd7/src/hamster/client.py#L102-L104


Then through dbus to
https://github.com/projecthamster/hamster/blob/b200d1007e43495fb6c466bca6c6dd478ae49bd7/src/hamster-service#L138-L144

then

https://github.com/projecthamster/hamster/blob/b200d1007e43495fb6c466bca6c6dd478ae49bd7/src/hamster-service#L114-L117

and

https://github.com/projecthamster/hamster/blob/b200d1007e43495fb6c466bca6c6dd478ae49bd7/src/hamster-service#L114-L117

This last one is quite puzzling...

From git blame (either from `git gui` or from [github](https://github.com/projecthamster/hamster/blame/b200d1007e43495fb6c466bca6c6dd478ae49bd7/src/hamster-service#L114-L117)) helped.
Here is the relevant commit:
https://github.com/projecthamster/hamster/commit/80110affd6f0c3a91d739c09a78dffe7c06976a1
After searching for `toggle`, it looks like work in progress.

Help would be appreciated here.

Last pointer, perhaps it should be better to solve #242 first, because that might affect windowing ?

**Comment by GeraldJansen** [comment]
I have found that this issue does not exist when using XFCE. Under XFCE, the `hamster toggle` command does nothing, as you discovered, however, the overview window does rise to the foreground with `hamster [overview]` and when launched from the menu and from xfce-hamster-plugin.

**Comment by ederag** [comment]
Under KDE, `src/hamster-cli overview` brings an overview window to the foreground each time,
resulting in several superimposed overview windows. Is it different in XFCE ?

**Comment by GeraldJansen** [comment]
Same under XFCE when running in development mode. However, behaviour is correct once installed, i.e.` /usr/bin/hamster [overview]`. (Using current master on XFCE 4.12)

**Comment by ederag** [comment]
That's interesting. Confirmed under LXQt: works when installed.
Definitely points to solving #242 first if it is indeed a gnome issue.

**Comment by ederag** [comment]
That was a bug in Gtk `present`, [worked around](https://gitlab.gnome.org/GNOME/gtk/issues/624#note_119092) in #516.
