### ISSUE TITLE
Cannot add acitivity description form the "update activity" window

### ISSUE THREAD

**Issue by sliwowitz** [projecthamster/hamster#305]
I use the fedora 23 package which got updated to hamster 2. I cannot add descriptions to activites using the "update activity" window:
- if I start a new activity from the shell extension everything is OK:
  - I enter "name@category, description" and it works
- if I "add earlier activity", description is ignored (I enter it, click save, and it disappears)
- if I modify an existing activity which had no description (the "update activity" window), newly entered description is ignored again

**Comment by axelsimon** [comment]
I'd like to add some information to this.
If you add some tags, then anything after the #tags gets dropped. If you put it before the tags, it gets saved as the category (stuff@category my description, #tag1, #tag2).

Using the trick in issue #295 however, one is able to add a description after the tags, by entering it in the description box.

**Comment by GeraldJansen** [comment]
Is this not solved by #403 which fixed #295? I.e. the description is taken from the separate description input box, which is now visible. It is not clear to me that it is desirable to allow description input from two areas of the "Update activity" and "Add earlier activity" widgets. In, the current behaviour is a bit strange for updating or cloning an activity with a description in that the description is replicated in two places, making it unclear where any edits should be performed. For example:
![Screenshot_2019-05-19_20-00-25](https://user-images.githubusercontent.com/31414956/57986111-fa8d4980-7a70-11e9-8b7d-46d4e3d330c1.png)

**Comment by sliwowitz** [comment]
I have not used hamster for quite some time, as it, unfortunately, went downhill - first the usability with bugs like this one, and ultimately the shell extension not working on any of my machines (recent Ubuntus and Fedoras).

Anyways I just installed it to test it - the separate description input is cool, and updating the description works from there.

The top input which shows the already added description is strange indeed, and it seems to me that it's still not working - i.e. If i change or add the description in the top input field, it is still not saved.

**Comment by ederag** [comment]
I have been  working on it, fully agree with both of you, and need feedback on the design.
Currently, I would tend to
1) Accept a description entry "inline" (after comma),
  in order to allow people used to the command line to get a familiar workflow
  (they will often be tempted to enter it this way, and it is not good to ignore an entry, IMO)
2) Only show the description in its box, once validated
  (e.g. when editing an existing activity)
3) If a description is given inline (after comma), with another one already in the box,
  if save is attempted, raise an error window and do nothing.
  The error window message could be
  "Attempted to enter a description inline (after the comma), while another description is already in the description box".
4) Display "Enter description here" in italic and a dim color if there is no description yet.

**Comment by GeraldJansen** [comment]
That all sounds good to me! A reusable error/warning/alert dialog could be useful in other cases too, for example #311.

**Comment by sliwowitz** [comment]
Agreed. I like it as well.

I don't know how's the shell extension supposed to work as of now, but if I remember correctly, it was a single line input, so it would be good if entering a new activity would allow the same workflow/syntax here and in the extension. 

Would it be possible to use either input when entering new activity? That is - one or other, but not both?

**Comment by ederag** [comment]
> Would it be possible to use either input when entering new activity? That is - one or other, but not both?

Exactly, either commandline-like or box, but not both.

**Comment by ederag** [comment]
Should be fixed,
please give feedback on PR #430.

**Comment by ederag** [comment]
Thanks for the report and for all the feedback !
