### ISSUE TITLE
Distributed databases and syncing

### ISSUE THREAD

**Issue by philtweir** [projecthamster/hamster#322]
Having had issues syncing between machines using Hamster, I was trying to work out what would be necessary to have replication to a central DB when connectivity is available. It looks like adding an optional alternative to src/hamster/storage/db.py using Python-PouchDB might be practical - this would allow for syncing to/from a CouchDB server without having to worry about the syncing details.

I'd be up for looking into this, but keen to know whether there is a preference for how this should be done or whether there is another preferred approach?

**Comment by elbenfreund** [comment]
Hello and welcome philtweir :)
This is an often requested feature. As you have figured looking at the code, adding another storage backend is not as simple as one would hope due to some architectural limitations. Currently there is an [refactored version](https://github.com/elbenfreund/hamsterlib) being developed by me that aims to avoid some of the difficulties in the current codebase. One major benefit is that it leverages the power of SQLAlchemy and as such provides access to distributed databases out of the box. If that is not enough, it also provides a plugable backend interface that allows for easily extending our storage options.
If those aproches look promissing to you, you may want to hold off investing time in a seperate solution. Right now, there is some work underway to raise project hamsters activity levels and potentialy change its ownership. Depending on the current owners feedback the solution you are looking for could be implemented relativly soon or not, so we are somewhat in limbo on that right now.

**Comment by philtweir** [comment]
Cool, thank you elbenfreund :) sounds good. Happy to hold off - that sounds much more logical - the detailed feedback is much appreciated!

**Comment by elbenfreund** [comment]
Hello philweir,

so, projecthamster is currently in a vibrant state of transition. The bad needs is: Unless somebody else steps up, further work (including bugfixes, review of PRs) is unlikly to happen on the original ``hamster`` repository. Instead, all work is directed towards the ``hamster-lib/cli/dbus/gtk`` repositories.
Those later repos build on top of our new codebase which hopefully will allow us to work in a more maintainable and modular fashion. If you are interested in the details, feel encouraged to check out the new [website](projecthamster.org).

Whilst the rewrite is not prime time ready, the cli version can be taken for a spin already and fully supports remote databases via SQLAlchemy. The documentation for it is not really there yet (but configuration should be straight forward if you ever used SA), and it still misses a lot of the original features but it should give you an idea of our current direction.

If you still feel that you got spare resources and want to work on project hamster, we would be very happy to have on board. :)

**Comment by philtweir** [comment]
Thanks for the update elbenfreund! I will try and get a look as soon as I can and, when my workload lightens a bit, see what I can do :)
