### ISSUE TITLE
Future of project hamster

### ISSUE THREAD

**Issue by elbenfreund** [projecthamster/hamster#323]
To all parties interested, :)
@toupeira @tbaugis 

project hamster is a great and useful contribution to the free software desktop.
Whilst its usefulness is undisputed it seems also undeniable that its current state
is rather unmaintained.
To be clear about this: this is not a complaint but a personal observation.
I think it is absolutely understandable that live gets in the way of things and we all know that there
is more often then not a schism between what "we want to get done" and "what we manage to get done".
However, ever so often project hamster attracts new people and potential contributors who I fear are
often discouraged, amongst other reasons, by this lack of feedback and direction.
We currently have 110 issues and 15 open PRs.

Because it is easy to complain and state the obvious but hard to make things better I am offering to step up and would offer to take over project hamster _IF_ this is desired by the current project owner and maintainer. Just like everyone else I have plenty of other work and engagements to entertain myself with if you decide to decline :)
So please do not think of this as takeover but merely as an offer to take responsibility for the little furry hamster I have come to care for quite a bit.

A short look into work of mine on refactoring/impoving (still WIP, but it should give a decent idea of what to expect) various aspects  of hamsters codebase will surely provide me with the needed credentials to prove my willingness to follow up with actions not just words as well as my ability to do so
in terms of code quality, procedure and and long term time contribution.

As a final remark, independent of your decision on the matter I want to express my explicit and verbal gratitude for @tbaugis  and @toupeira long lasting and valuable effort in making `Project Hamster` the success it is today.
- [hamster-lib](https://github.com/elbenfreund/hamsterlib)
- [hamster-cli](https://github.com/elbenfreund/hamster_cli)
- [hamster-dbus](https://github.com/elbenfreund/hamster-dbus)
- [hamster-gtk](https://github.com/elbenfreund/hamster-gtk)

**Comment by border0464111** [comment]
Project Hamster do the job pretty well IMO and is quite stable. I guess most users would be pretty upset if anything affect their habits. On the other hand, there is always room for improvement and new features. 

Having 15 open PRs in queue is shure a BIG turn off for potential contributors.

From a user perspective. I would tend to be happy to see new people and see the project foward. But im also scared it would change what I like of project-hamster. 


 - Just a random user personal point of view. aka Fred

**Comment by elbenfreund** [comment]
The vast majority of my suggested changes/improvements do not affect the average user at all :)
It is mostly a rewrite of the underlying codebase in order to be more pythonic, tested, standard compliant and easier to maintain. I absolutely agree that after the 'recent' switch from ``hamster-applet`` to ``hamster-time-tracker`` we should try to stick with the current user workflow where feasible.

**Comment by elbenfreund** [comment]
For those interested,

Tom (@tbaugis) was most supportive and accepted my offer in the most friendly way. Beginning next week I will try to setup some additional infrastructure and write up some general outline of what I consider our short and midterm goals/priorities with Project Hamster.
I want to invite everyone interested to join me in this endeavor of using our current momentum to revitalize this little fur ball.

**Comment by border0464111** [comment]
G!

**Comment by border0464111** [comment]
Great news ! :)

**Comment by toupeira** [comment]
Hey @elbenfreund, I want to apologize for neglecting my maintenance duties and am happy you're willing to step up and take over! And really all the thanks belong to @tbaugis, I never got around to doing much :)

I've been pretty distracted with other things so unfortunately I don't think I'll be involved with the project anymore, so consider this my official resignation. Thanks a lot for picking up the torch, and from the sounds of it I'm sure you'll be doing a great job!

Let me know if you need anything from me, otherwise I'm going to remove myself as owner as well. For the shell extension you need to create an account on extensions.gnome.org and then contact them [somehow](https://www.gnome.org/contact/) (I ended up going through #gnome on IRC) to change the ownership. And there's also the old blog at https://projecthamster.wordpress.com/, if you have a Wordpress account I can give you access to that too.

**Comment by elbenfreund** [comment]
Great to hear from you @@toupeira :) And although you may think you did not get around doing much it was your warm and encouraging welcoming that convinced me to actually get invested in this project.

Thank you for the pointers regarding the extension. About the blog: I registered "http://projecthamster.org" and will set up some basic meta-information/news there soon. So i think the wordpress blog can be shut down if that is alright with you.
And maybe, just like for @tbaugis, now that you do have no responsibilities for projecthamster anymore you may come back some later day with rekindled motivation and time to help us out :)

Best of luck with all your future endeavors and thanks for all your work/time. Eric.

**Comment by border0464111** [comment]
@toupeira you should not minimize the job the dot connectors :) community management is often neglected but it can kill a project harder then bad code. 

@elbenfreund  im webdev, I could take tasks for the website.

**Comment by toupeira** [comment]
@elbenfreund / @border0464111 thanks for the kind words, I also wish you all the best! Not sure if I'll ever be back since I recently started to get sucked into Emacs and org-mode which does a great job with time-tracking as well, though I do miss having a fancy GUI ;-)

I'll leave the decision to shutdown the Wordpress blog to @tbaugis since it also contains some of his other projects.

**Comment by toupeira** [comment]
I added some information about the [release process for the shell extension](https://github.com/projecthamster/shell-extension#release-process) and noticed that the UUID still references the Wordpress URL. Not sure if the rewrite is fully backwards compatible, if not you might want to use a new UUID to separate the two versions. Otherwise it's probably best to keep the old one and wait until Gnome 4 breaks everything all over again ;-)

**Comment by slick666** [comment]
Hey All, I'm coming back after many years I'm sorry to see that things have fallen a bit behind but I would be happy to help get things moving again. I would love to see this project git up on travis or some other CI/CD path and to start merging down the community updates and updating the docs where I can.

**Comment by elbenfreund** [comment]
Welcome back @slick666 :) Once you get up to speed with the current situation you will find that all components of the current rewrite effort but the GTK frontend actually are on Travis and feature a quite decent coverage. Whilst ``hamster-gtk`` has just received a major set of tests (pushing it over the 85% benchmark) as well I still fail to get GTK to play nice with tox. So Travis currently just checks for style/syntax. But still, this seem a major step forward.

My immediate recommendations would be to subscribe the new [mailinglist](http://lists.projecthamster.org/listinfo.cgi/hamster-dev-projecthamster.org) and check out the new [website](http://projecthamster.org) for some context

**Comment by ederag** [comment]
Closing; discussion about hamster future may continue in #433.
