### ISSUE TITLE
'Add Earlier Activity' combo box doesn't work under Wayland

### ISSUE THREAD

**Issue by hedayat** [projecthamster/hamster#339]
In "Add earlier activity" window under wayland (Fedora 25), the combo box doesn't appear.

**Comment by elbenfreund** [comment]
Thank you for your feedback, it is much appreciated.

Project hamster and its various sub-components is currently undergoing some major changes. We prepare the introduction of a rewritten codebase for most of the underlying functionality. A direct consequence of this is that it is unlikely that any open/new bugs within the current/old codebase will be fixed (unless someone steps up and offers to do so) as most resources currently available will be invested in making the rewrite prime time ready.

**Comment by ederag** [comment]
Thanks for the report.
What "combo bow" is this ? The drop-down menu for suggestions ?
Which version ?
Is is still the case with current master ?

**Comment by hedayat** [comment]
Yes, the drop-down menu for suggestions.
I'm using Fedora 2.0 version. I've not tried current master yet. If needed, I should try.

**Comment by ederag** [comment]
Thanks for the precisions. The bug is most probably still there.
If you want to look into that,
the activity entry widget is added to the edit activity window there:
https://github.com/projecthamster/hamster/blob/2e52d217daca4cd3e034fa619e18f871038aa639/src/hamster/edit_activity.py#L50
And the drop-down that does not show up, is ironically called popup:
https://github.com/projecthamster/hamster/blob/2e52d217daca4cd3e034fa619e18f871038aa639/src/hamster/widgets/activityentry.py#L206

As usual, it is advised to discuss here prior to making extensive changes.
But any chance it was https://bugzilla.redhat.com/show_bug.cgi?id=1264355 ?
Maybe these are also relevant: https://wiki.gnome.org/Initiatives/Wayland/GTK%2B

Feedback from users with a more recent version of Gtk3/Wayland would be useful too.

**Comment by hedayat** [comment]
Well, to make my report more complete:
The bug still exists in Fedora 29, with GTK 3.24.1. It should be pretty recent GTK/Wayland combination.

And No, it was not that bug about misplaced windows. And to make the report more precise, it seems that the window actually appears, but it immediately disappears as if some key is pressed to hide it without selecting any entry.

But maybe the 'Popups and grabs' section in GTK Wayland wiki is related to this problem.

**Comment by ederag** [comment]
Thanks for the precisions.
There is some absolute positioning in
https://github.com/projecthamster/hamster/blob/2e52d217daca4cd3e034fa619e18f871038aa639/src/hamster/widgets/activityentry.py#L443
that should be avoided according to
https://gitlab.gnome.org/GNOME/gtk/issues/683
[gdk-window-move-to-rect](https://developer.gnome.org/gdk3/stable/gdk3-Windows.html#gdk-window-move-to-rect) should be used instead.
That will have to wait though, unless someone steps in.

**Comment by ederag** [comment]
Possible temporary workaround ? From https://wiki.archlinux.org/index.php/Wayland
> XWayland provides a compatibility layer to seamlessly run legacy X11 applications in Wayland

**Comment by ederag** [comment]
Should be fixed by #527. 
The `TimeInput` still need some work, but at least the popup positions are correct.

**Comment by hedayat** [comment]
Great, thanks :)
