### ISSUE TITLE
Week view is set for next week

### ISSUE THREAD

**Issue by amig** [projecthamster/hamster#392]
As you can see in the screen capture, Although today is 28th the week view is for a week starting on Saturday, March 2nd.
This happens every week and not just today.

![menu_003](https://user-images.githubusercontent.com/203434/53551297-a180da00-3b41-11e9-8230-99db768178aa.png)

My locale is: 
LC_TIME="en_IL"

first_workday 1

As you can see in Ubuntu's calendar, week view is correct (week starts on Sunday).

![calendar_004](https://user-images.githubusercontent.com/203434/53551438-ff152680-3b41-11e9-84f2-24e25dc581a9.png)

Any suggestions?

**Comment by ederag** [comment]
The current week seems correct for me (snapshot 6d9c978703561a9c4620b6de0d9100ee1c649fb3): 25/02-03/03.
It looks like you are using version 1 hamster, right ?
Please try with the snapshot given above (ask here if you need further [instructions](https://github.com/projecthamster/hamster#trying-the-development-version)).

**Comment by amig** [comment]
I'm using Ubuntu 18.04.
hamster-applet 2.91.3+git20120514.b9fec3e1-1ubuntu3
hamster-indicator 0.1+037dd2e-0ubuntu3

Do not understand what I should do.

**Comment by ederag** [comment]
The version you are using is good, but old and unmaintained (unless someone steps in).
Several bugs have been fixed in the current `master`, but there are other limitations.

The simplest thing to do is to stick with the old one,
but we definitely need more testing, and clear feedback such as your original post
would be greatly appreciated for the development version.

If you want to try it, you may
- backup your `hamster.db`
 (check with  `ls -l ~/.local/share/hamster-applet/hamster.db` 
   that it has indeed been changed recently)
- [clone](https://help.github.com/en/articles/cloning-a-repository) the hamster repository
- Get a specific snapshot (commit), e.g., for 6d9c978703561a9c4620b6de0d9100ee1c649fb3
  `git checkout 6d9c978703561a9c4620b6de0d9100ee1c649fb3`
- Then follow these [instructions](https://github.com/projecthamster/hamster#trying-the-development-version)

Please do ask here if some explanations are missing.

**Comment by amig** [comment]
After cloning the project, when I tried to checkout to the above commit I got:
`fatal: reference is not a tree: 6d9c978703561a9c4620b6de0d9100ee1c649fb3`
Nevertheless, I looked at the instructions and they do not address my system (Ubuntu 18.04):
1. The `/usr/lib/python3.6/` folder does not include a `site-packages` folder
2. The `/usr/lib/python2.7/` folder, also does not include the `site-packages` folder
3. The later (python2.7) has instead a `dist-packeges` folder that includes the `hamster` folder

This makes me wonder if it can be installed on my system.

**Comment by ederag** [comment]
> fatal: reference is not a tree

Sorry, I thought that PR commits were all available.
For now, just use the cloned master as is.

About installation, this should help: https://github.com/projecthamster/hamster/issues/221#issuecomment-462094920.

**Comment by ederag** [comment]
The link to the example was added to the `README.md` (5771c287aa5e998efaa85766c5fa08f61866f545), to clarify what "adapt" the path means.

**Comment by ederag** [comment]
The installation process is going to be improved (PR #421).

Closing, since this issue is thought to be solved in the development version.
Thanks for contributing to hamster improvement !
