### ISSUE TITLE
Bad support of gnome dark theme

### ISSUE THREAD

**Issue by ikus060** [projecthamster/hamster#424]
Similar to #164, The UI is not properly displayed for dark theme. 
![image](https://user-images.githubusercontent.com/921251/61592063-07770800-ab9c-11e9-8d9b-d19954db3062.png)
The left pannel with wither text on gray background is not a very good contrast.
The Stats at the bottom are not readable.

Would be nice to either support dark theme or to enforce light theme ?

**Comment by ederag** [comment]
Thanks for reporting with a screenshot.
What is your version ?
As stated in https://github.com/projecthamster/hamster/issues/164#issuecomment-468037120, this is already fixed in master.
And it will be available in the forthcoming [2.3](https://github.com/projecthamster/hamster/issues?q=is%3Aopen+is%3Aissue+milestone%3Av2.3) release (next few months).

**Comment by ikus060** [comment]
That is version 2.2.2. didn't notice the pull request was only in master
branche. Qu'il vive a trial to master and provide feedback.

**Comment by ikus060** [comment]
At least the color sheme make more sens now (with master branch).
![image](https://user-images.githubusercontent.com/921251/61739517-903ba280-ad5a-11e9-9287-6040b919be69.png)
Closing this issue.

**Comment by ederag** [comment]
Thanks for the feedback !
