### ISSUE TITLE
Hamster "Time Tracker" and "Time Tracker overview" start the same UI

### ISSUE THREAD

**Issue by Forage** [projecthamster/hamster#446]
After installing Hamster (today's master) on Ubuntu 19.04, both "Time Tracker" and "Time Tracker overview" are giving the exact same resulting UI:
![Screenshot from 2019-09-19 15-05-45](https://user-images.githubusercontent.com/550915/65246524-11ab7900-daef-11e9-84fb-864076cda783.png)
There used to be a difference between the two. What could be the problem here?

**Comment by GeraldJansen** [comment]
In the port to gtk3 the day view and the overview were united and are the same thing. Clicking on the date allows one to choose any day, week, month or custom interval to display in the overview. The search button allows one to further restrict the displayed activities. Then one can export the displayed activities as an html report or xml file, for example. Probably only the "Time Tracker" should be installed at this point.

**Comment by Forage** [comment]
In that case yes, the "Time Tracker overview" desktop file is redundant now.

Too bad, I quite liked having the small entry dialog at hand.

**Comment by ederag** [comment]
Thanks for the report.
Agreed, removing `data/hamster-time-tracker-overview.desktop.in.in` makes sense.
Setting v3.0 milestone for that.

About the small entry dialog,
the overview serves also this purpose now, as Gerald said,
and that allows to clone entries from previous days, which is an improvement over v1.
If the idea is to quickly have an entry window available, it is possible to reduce the overview size,
and use the + button to add an activity.
It's been a while since using v1, please elaborate if I'm missing the point.

The edit_activity window is currently under heavy work (not pushed yet) to add separate fields,
so part of the v1 experience will be available again. Tags editing will be back !

**Comment by Forage** [comment]
Never mind about the smaller dialog. Now that the latest sources are working nicely with the GNOME extension again (version https://github.com/projecthamster/hamster-shell-extension/pull/312) the need for that dialog became redundant again.

**Comment by ederag** [comment]
Now fixed by Gerald in PR #452 (thanks !)
