### ISSUE TITLE
"Add earlier activity" dialog usage is not obvious

### ISSUE THREAD

**Issue by Forage** [projecthamster/hamster#451]
Using the "Add earlier activity" dialog of the latest sources is of no use at the moment, but I'm having a hard time determining if it's by design or simply buggy.

![Screenshot from 2019-09-20 11-16-25](https://user-images.githubusercontent.com/550915/65315338-327bd900-db98-11e9-989a-6c5166a4f372.png)

It's a dialog I use quite a lot and I expect it to allow me to quickly add an activity that started, well, earlier, by specifying it's name and the starting time.
There's this timeline at the top that does not allow me to do anything more than changing the day (with the left/right arrow icons).

Clicking on the downwards arrow gives me a list of past items, but displayed at the top left of the screen, separated from the dialog completely.

These dropdown items have the options "[start now]", "[start activity -n minutes ago]" and "[clear]" but it is not clear to me how this is supposed to work.

If it's 11:25 now, how am I supposed to quickly start an activity at 09:15?
Am I really supposed to calculate the number of minutes myself? 
And how do I actually provide the time?
What is the (intended) purpose of the timeline at the top?

Using Ubuntu 19.04 (GNOME Shell).

**Comment by GeraldJansen** [comment]
This dialog should be named "Add activity" because it can be used to add past, present and even future activities. It is the key interface to create new activity items for those who cannot or prefer not to use external programs like the Gnome shell plugin. Basic information on data input is given in the "Input" help page. By default the new activity will be started at the current time, as this is expected to be the norm for someone actively tracking their time usage. To specify an earlier time, you can enter a specific time in front of the activity as say 09:15, 09.15 or simply 0915. If you don't remember the exact time but think you've been working already for say 20 minutes on the current activity, you can enter that as -20 instead of giving the wall clock time. You can also specify the end time for completed activities, separated from the start time by either a '-' or by a space. Concerning time input, you may find some of the other open issues to be of interest.

In the README it is openly admitted that some of the nicety of the old GUI got lost in the transition to gtk3, basically because no-one stepped up to re-implement it. The ability to click on the time-line to set times is one of those things. However, if you have already entered some activities, you will see the time blocks highlighted on the time-line. I guess this feature can help to avoid entering overlapping activies. 

(Aside: a kinder and less offensive title would be ""Add earlier activity" dialog usage is not obvious". Please consider that there is only a single maintainer of this project and he has basically given up his last two summer vacations and much free time in the evenings for more than a year now to get this show back on the road.)

**Comment by Forage** [comment]
Thanks for the clarifications.

So you're in trouble if your activity happens to start with a time? Or do you need to separate time and activity title with some sort of separator like the comma between title and description/tags?

I think I'd prefer having actual physical controls to specify time somehow. An open text field is too cumbersome and error prone.
At least some form of partial fancy input guidance would be appreciated. In the lines of automagically showing a time selector if you start typing a number or a minus or some form of autocompletion.
I'll see if I can dig up some more examples.

If the intention is to, at least for the time being, keep the unguided free time input as is, it would be a good idea to have a help/hint text permanently present to describe the options.

Are you able to reproduce the issue where the drop-down list (the expended values) is actually shown completely separated from the actual dialog when you click the downwards arrow?

I meant "not helpful" in the sense that it isn't self-explanatory and "buggy" because, well, it appears to be ;) Just being direct, not sugarcoating it and no offence intended. It doesn't mean I don't appreciate the effort you guys are putting in the application. It's great to see it working and moving forward again.

**Comment by GeraldJansen** [comment]
Fortunately no-one has asked for the feature of being able to start an activity title with a valid time value ;-)

Concerning input guidance, perhaps the easiest thing would be to put a '?' button at the end of the input field which would open the Input help page. 

For me the drop-down suggestion list is directly under and attached to the input field. I'm not able to take a screenshot because it disappears as soon as you make another keystroke or mouse click. The only slightly strange thing is the way it extends downwards past the edge of the input dialog, but the only ways to avoid that would be to offer very few suggestions or enlarge the whole dialog box.

**Comment by ederag** [comment]
Thanks, I had other activities too during vacations,
but it is true that I develop hamster only on free time.
And kindness is a better fuel.
The other title would have conveyed the same message, while feeling gentler indeed.

Input is described in the help pages, accessible from the "settings" menu, 
and now also available [online](
https://geraldjansen.github.io/hamster-doc/input.html) thanks to Gerald.
Maybe it was not clear that it was relevant to the gui ?

The drop-down list is at its place on any X11 platform tested so far.
Are you under wayland by chance (thinking about #339) ?

**Comment by Forage** [comment]
I finally got round to test the dropdown in a non-wayland environment and you are spot on. That issue is only present under wayland.

There was really no need to justify yourself as I tried to explain before. I'm not blaming anyone for anything.
But since I'm now visiting the GitHub site one my desktop system instead of my phone I can finally edit the ticket title as well.

I think the matter of providing start and stop times is currently too complicated and too important at the same time that a description in the help is too far away.
The other day I ran into the issue where I wanted to stop an ongoing activity earlier but again couldn't find an obvious way to do it.
I suppose I had to manually add the stop time after the start time in the same activity text input field, but decided to not even try it. Time tracking needs to be an extremely trivial task. As soon as you loose time having to figure out how to do it you miss the point it doing the tracking in the first place.
So I'm reverting back to the old version for the time being.

For the same reason as coming back to this with some delay I haven't finished my search for some examples of alternative ways to provide times either.

Does the fact that separate input fields for start and end time haven't been implemented again because no one did it yet also mean that it wasn't the intention to implement it again as before to begin with? Does it need to be different than before for some reason?

**Comment by Forage** [comment]
And by that you can consider this ticket a duplicate of #439

**Comment by ederag** [comment]
Indeed, and thanks for editing the title.

> I suppose I had to manually add the stop time after the start time in the same activity text input field

There was a hint in the dropdown (the "stop" suggestion), 
that was added precisely to help new users,
but since on wayland it is not correctly visible, that did not help at all in your case.
Let's hope someone will find a workaround for wayland (#339).
