### ISSUE TITLE
Drop-down should match currently-entered time

### ISSUE THREAD

**Issue by fantasai** [projecthamster/hamster#515]
[Trying to note down the little things that trip me up in the new UI.]

Steps to Reproduce:

1. Start a new activity. The start time is pre-filled to right now.
2. Insert cursor on the time, edit. e.g. from 16:05 to 16:00
3. Try to pick something from the drop-down to auto-complete the activity.

Actual Results:
Notice every choice for activity is based off 16:05 (original start time) instead of 16:00 (current value)

Expected Results:
Auto-completes should be based off of 16:00 (edited start time, i.e. current value)

**Comment by ederag** [comment]
Thanks for the report. 
UI fixes will be investigated after the infrastructure changes (two PR in preparation)
and the wayland bug fix.

At step 3 "drop-down to auto-complete the activity" is not the cmdline dropdown (from the top entry),
because that one works fine (e.g. it is updated after any change to the start time).

So I guess that after typing you want to get up or down by known increments.
If everyone agrees, that would make sense, indeed.
Things to consider: what happens when the entry is invalid ?

It might be much easier/cleaner to use fixed intervals, just selected the nearest one.
Would that be better ?

**Comment by ederag** [comment]
> Expected Results:
Auto-completes should be based off of 16:00 (edited start time, i.e. current value)

That's already the case:

![Screenshot_20200126_113502](https://user-images.githubusercontent.com/10962809/73133932-e9e59800-402f-11ea-85da-e9e986bc7a38.png)

**Comment by fantasai** [comment]
![hamster](https://user-images.githubusercontent.com/725717/73505329-06af0200-4387-11ea-8cde-2e78944c7506.png)

Sorry I wasn't clear. It's a problem with the top auto-complete, where you enter the start time and activity together. Here's a screenshot. This is running 5a3f02a29630566c4326342e09d2e43cfe7538a3

**Comment by ederag** [comment]
Thanks for the precisions. This has been fixed meanwhile,
and polished in #543.
