### ISSUE TITLE
Migrate from GConf to GSettings

### ISSUE THREAD

**Issue by eheintzmann** [projecthamster/hamster#64]
With GNOME 3.0 (april 2011), the GNOME Project decided to discontinue GConf.
It won't be maintained anymore: bugs and security holes will not be fixed.
Thus, Hamster shouldn't depend on GConf any longer.
Please, migrate to GSettings.
GStettings is the official GNOME replacement for GConf, and the GNOME project
is porting all of its applications to it:
https://live.gnome.org/GnomeGoals/GSettingsMigration

You will find the official from GConf to GSettings porting guide at:
http://developer.gnome.org/gio/stable/ch31.html

**Comment by ederag** [comment]
Here is an example of a migration to gsettings:
https://github.com/xflux-gui/fluxgui/pull/112/commits
especially
https://github.com/xflux-gui/fluxgui/pull/112/commits/aea7d3e32ebbdeec472f95fc8a344c8c9ea30ebe and
https://github.com/xflux-gui/fluxgui/pull/112/commits/4cb62e3acb2761318e6e4999f8b629251f5c973d
[there are other relevant commits for settings in this PR]

**Comment by GeraldJansen** [comment]
Migrating from gconf to dconf should be done for v3.0 or v3.1 if they should become  "the stable version for years to come"(https://github.com/projecthamster/hamster/issues/433#issuecomment-524579649)

**Comment by ederag** [comment]
No gsettings for for `v3.0`.
OK for `v4.0` (that is a major change).

**Comment by City-busz** [comment]
This would be important on Arch Linux, because we are trying to get rid from GConf, and I had to remove Hamster from the official repositories because of this.

**Comment by ederag** [comment]
Sorry.  This is a huge change, a new framework to me, and too many jobs already started.
I was hoping to get another year to tackle this task...

If anybody knows how to do that, please fork, and advertise your progress here,
so that Arch Linux users can readily benefit from your work.

Ideally, do this work in a separate branch (say `gsettings-migration`), 
with only the minimal changes required to migrate without introducing bugs.
This would help creating a clean PR (please be nice to reviewers !).

The configuration machinery is located in
[`src/hamster/lib/configuration.py`](https://github.com/projecthamster/hamster/blob/master/src/hamster/lib/configuration.py)
For the installation, waf has the [glib2](https://waf.io/apidocs/tools/glib2.html) tool.
in particular, [glib_validate_schema](https://waf.io/apidocs/tools/glib2.html#waflib.Tools.glib2.glib_validate_schema) and [process_settings](https://waf.io/apidocs/tools/glib2.html#waflib.Tools.glib2.process_settings).

Please ask here for further informations on the hamster internals if need be.

**Comment by GeraldJansen** [comment]
Link updates:
https://wiki.gnome.org/Initiatives/GnomeGoals/GSettingsMigration
https://developer.gnome.org/gio/stable/ch34.html

**Comment by GeraldJansen** [comment]
Given our limited resources and knowledge, could we not just get rid of gconf and revert to a simple config file that lives next to the hamster.db (eg. ~/.local/share/hamster-applet/hamster.conf). This seems to be the approach taken in the rewrite (hamster_lib), using [configparser](https://docs.python.org/3/library/configparser.html).

**Comment by ederag** [comment]
Interesting possibility. `gsettings` offers more though (for instance concurrent modification).
We need a change to the configuration made from the overview to be reflected in `hamster-service`
without restart.
Is handling file monitoring ourselves easier than migrating to `gsettings` ?
Let's think again about that after v3.0 is out.

**Comment by ederag** [comment]
Fixed by @bgamari in #470, thanks again !
