### ISSUE TITLE
Executable availability

### ISSUE THREAD

**Issue by bioinfornatics** [projecthamster/hamster#651]
Dear,

After read the README file I try to get hamster from:
1. https://apps.fedoraproject.org/packages/hamster-time-tracker but they are a 503 error
2. flathub but thy are 0 result https://apps.fedoraproject.org/packages/hamster-time-tracker

Where can I get it ?

**Comment by matthijskooijman** [comment]
> https://apps.fedoraproject.org/packages/hamster-time-tracker but they are a 503 error

This seems to be a temporary problem on Fedora's end. If you are running Fedora, did you check their package installation tool to see if it's already available (might not be, hasn't been uploaded to Fedora since a long time).

> flathub but thy are 0 result

We've added flatpak support after our last release, so no releases are available yet (and I don't think we're registered on flathub yet either).

However, if you're willing to test our unreleased master version, you can find the latest build (top one) in the [list of workflow builds for the master branch](https://github.com/projecthamster/hamster/actions?query=branch%3Amaster), click the commit message and pick up the flatpak file from the "Artifacts" section. Installation instructions are in the README, I believe.

Alternatively, you can git clone master, or the latest release, and build and install it yourself, but that might not be the ideal solution (since it bypasses your package manager).

Let us know if that helped!

**Comment by bioinfornatics** [comment]
Thanks I will take a look

I wish to hamster team the best, see you
