### ISSUE TITLE
Inputting descriptions with single or double comma?

### ISSUE THREAD

**Issue by matthijskooijman** [projecthamster/hamster#657]
From https://github.com/projecthamster/hamster-shell-extension/issues/334:

> With hamster 3.0.2, if you type Activity@Category, task description in the shell extension, nothing happens. To get it to actually start, you need to type Activity@Category,, task description. This is likely related to the breaking change made in hamster that now requires two commas to separate descriptions:
projecthamster/hamster@42d3c05

> I think we should revisit that decision as it doesn't seem like a good decision to me. In particular when typing Activity@Category, #tag just works.

> But if we don't, then we somehow need to fix the shell extension. Something needs to happen when the user inputs something... either it creates an activity with some unexpected values, or it displays an error. But just dropping the user's input is wrong.,

And from https://github.com/projecthamster/hamster/pull/656#issuecomment-743337886

> I would love to see some discussion on projecthamster/hamster-shell-extension#334 and see wether we prefer to revert 42d3c05 here or find some other solution elsewhere.

**Comment by matthijskooijman** [comment]
w00ps, pressed ok too soon. Edited in the issue description above now :-)

As for the double comma, I also noticed that this had some special handling in the activity editing window that seems a little fragile. It seems that the description is also the only part that is not serialized into the cmdline, though it is editable from the commandline using the double comma I think.

Anyway, I wonder what the motivation for the double comma is. I guess it serves to distinguish a tag from the description? Maybe it allows starting the description with a hash, which is probably not otherwise possible? Would we mind?

I haven't looked too closely at this yet, though, just wanted to get this dicussion in a separate issue in the right place :-)

**Comment by GeraldJansen** [comment]
Basically the double comma emerged to satisfy the request of one user to be able to include a comma in the activity name. @mwilck argued against the change [here](https://github.com/projecthamster/hamster/issues/465#issuecomment-547335487) and I have to say I agreed with him then and still do.

**Comment by ederag** [comment]
> Basically the double comma emerged to satisfy the request of one user to be able to include a comma in the activity name.

You do not think this through. https://github.com/projecthamster/hamster/issues/465#issuecomment-557810768 + other reasons.

**Comment by GeraldJansen** [comment]
@ederag The fact that I didn't provide further opposition to the double comma doesn't mean that I liked it. In fact, I agree that the decision could and should be revisited. It could be done without reducing the rock solidness of the parser.

**Comment by mwilck** [comment]
My €0.019 [here](https://github.com/projecthamster/hamster-shell-extension/issues/334#issuecomment-744307057).

**Comment by ederag** [comment]
As a reference, here are the v3.0.0 rules (from the help):

1. Specify specific times as `13:10-13:45`, and "started 5 minutes ago" as `-5`.
2. Next comes the activity name
3. Place the category after the activity name, and start it with an at sign `@`, e.g. `@garden`
4. If you want to add a description, add a double comma `,,`.
5. The description is just freeform text immediately after the double comma, and runs until the end of the string or until the beginning of tags.
6. Place tags at the end, and start each tag with a hash mark `#`.
7. A double comma `,,` can also be placed to indicate the beginning of tags. Otherwise any `#` in the activity, category or description would be interpreted as a starting a tag.

Change between v2 and v3: Double comma before description and before tags.
Clear and simple, except perhaps for someone used to a single comma before description.

**Comment by matthijskooijman** [comment]
This was resolved by merging #663.
