### ISSUE TITLE
Starting a "recent activity" mis-uses @category

### ISSUE THREAD

**Issue by martinmagnusson** [projecthamster/hamster#666]
When "recent activities in meny" is set to >0 in indicator options, so that one can click a recent activity to re-start it from the indicator, starting a recent activity such as "A@B" will start an activity named exacly that with an unnamed category, instead of how I think it should be: an activity called "A" in category "B".

**Comment by matthijskooijman** [comment]
Hey @martinmagnusson Thanks for taking the time to report this issue, apologies for taking so long to respond.

I'm reading your issue and it indeed sounds like a problem. However, it's note entirely clear to me what "indicator" your are talking about? Are you talking about the gnome-shell extension? Or is this specific to some other environment? Also, what Hamster version are you running?

**Comment by GeraldJansen** [comment]
This issue should be closed because it probably refers to a long defunct version of Hamster. Current Hamster works as expected. A recent indicator utility is here: #679. Otherwise @martinmagnusson may be interested in a recent version of [hamster-shell-extension](https://github.com/projecthamster/hamster-shell-extension).

**Comment by matthijskooijman** [comment]
Agreed, let's close this. If @martinmagnusson wants to clarify and/or reopen, feel free.
