### ISSUE TITLE
Hamster 3.0.2 computes very high hours for dates long ago

### ISSUE THREAD

**Issue by MatNieuw** [projecthamster/hamster#689]
When I look at a period of 6 years, Hamster displays for some activities an extremely high number of hours for that activity and for the total, like 131513. The database was build using Hamster 1.0.4. between November 2015 and June 2020, then since yesterday (2021-November) with Hamster 3.0.2 . 
It happens already if I select period 2016-November to 2017-November, that tells me 41868 hours total. But 2015-November to 2016-November is OK.
Hamster 1.0.4 never showed this, and computed correct totals.

**Comment by MatNieuw** [comment]
Update: I found an un-terminated acivity at 2017-02-02. As soon as I include that day, Hamster shows the incorrect hours.
The reporting period was set from 2017-02-02 to 2017-02-02 , obviously there cannot be more that 24 hours, even in un-terminated activities.
I think best solution is that Hamster reports actual hours for un-terminated activities, from start of activity to the end of the reporting period. Then un-terminated activities will still be easy to find out, e.g. set a en reporting date a year in the future, and keep increasing the start reporting date until the numbers drop significantly.

**Comment by GeraldJansen** [comment]
I actually rather like current Hamster's behavior because I immediately see an un-terminated activity in the overview at the start of the next working day. Then I still have some chance of remembering the approximate end time and can fix that activity right away. With the older Hamster, I remember not finding such activities until my monthly invoice preparation.
